# ======================================================================
#
#				Include or header file for WATDRN_Standalone
#
# ======================================================================

# ======================================================================
# Directory of source code
# ======================================================================

# To build from the current directory:
DIR_REPO=.

# ======================================================================
# Include the following directories in the source file searching path
# ======================================================================
VPATH=	$(DIR_REPO)/src: \

# ======================================================================
# Object files needed to build reading netcdf
# ======================================================================

#Modules 
OBJECTS=    check_stat.o nc_io_file.o \
			WATDRN.o WATROF.o \
			WATDRN_SA.o 